### ISSUE TITLE
jinja2.exceptions.UndefinedError  jinja2.exceptions.UndefinedError: 'task_id' is undefined

### ISSUE THREAD

**Issue by aueskinj** [aueskinj/coursera_projects#1]
Traceback (most recent call last):
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rhyme/Desktop/coursera_projects/routes.py", line 33, in edit
    return render_template('edit.html', form=form)
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/rhyme/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/rhyme/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/rhyme/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/rhyme/Desktop/coursera_projects/templates/edit.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/rhyme/Desktop/coursera_projects/templates/base.html", line 32, in top-level template code
    {% block main %}{% endblock %}
  File "/home/rhyme/Desktop/coursera_projects/templates/edit.html", line 5, in block "main"
    <form action="{{ url_for('edit', task_id=task_id) }}" method="post">
  File "/home/rhyme/.local/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/rhyme/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 2177, in build
    rv = self._partial_build(endpoint, values, method, append_unknown)
  File "/home/rhyme/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 2055, in _partial_build
    endpoint, values, self.default_method, append_unknown
  File "/home/rhyme/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 2067, in _partial_build
    rv = rule.build(values, append_unknown)
  File "/home/rhyme/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 1038, in build
    return self._build_unknown(**values)
  File "<werkzeug routing>", line 1, in <builder:'/edit/<int:task_id>'>
    
  File "/home/rhyme/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 1257, in to_url
    value = self.num_convert(value)
jinja2.exceptions.UndefinedError: 'task_id' is undefined

**Comment by aueskinj** [comment]
Issue with db, fixed by  wrapping the db inside the Flask application context using the app.app_context() context manager.
